-- MySQL Script generated by MySQL Workbench
-- 08/14/24 16:17:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ControleFinanceiro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ControleFinanceiro` ;

-- -----------------------------------------------------
-- Schema ControleFinanceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ControleFinanceiro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ControleFinanceiro` ;

-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`meses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`meses` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`meses` (
  `id_mes` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_mes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`categorias` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `tipo_despesas` ENUM('N', 'F', 'V') NOT NULL DEFAULT 'N',
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`despesas_fixas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`despesas_fixas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`despesas_fixas` (
  `id_despesa_fixa` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `categoria_despesas_fixas_id` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `vencimento` DATE NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'nope',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  `active` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`id_despesa_fixa`, `categoria_despesas_fixas_id`),
  CONSTRAINT `fk_minhas_depesas_fixas_categoria_despesas_fixas`
    FOREIGN KEY (`categoria_despesas_fixas_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_minhas_depesas_fixas_categoria_despesas_fixas_idx` ON `ControleFinanceiro`.`despesas_fixas` (`categoria_despesas_fixas_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pessoas` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `segundo_nome` VARCHAR(45) NULL,
  `terceiro_nome` VARCHAR(45) NULL,
  `sobre_nome` VARCHAR(45) NOT NULL,
  `segundo_sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`bancos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`bancos` (
  `id_banco` INT NOT NULL,
  `nome_abreviado` VARCHAR(45) NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `site` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_banco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`cartoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`cartoes` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`cartoes` (
  `id_cartao` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `banco_id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `numero` VARCHAR(16) NOT NULL,
  `vencimento` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `funcao_debito` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `funcao_credito` VARCHAR(45) NOT NULL DEFAULT 'Y',
  `limite_credito` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `limite_cheque_especial` DOUBLE(6,2) NULL DEFAULT 0.00,
  `dia_vencimento_fatura` DATE NOT NULL,
  `cartao_principal` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `encargos` DOUBLE(6,2) NULL,
  `multa` DOUBLE(6,2) NULL,
  `juros` DOUBLE(6,2) NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  `active` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`id_cartao`, `pessoa_id`, `banco_id`),
  CONSTRAINT `fk_cartoes_pessoas1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartoes_bancos1`
    FOREIGN KEY (`banco_id`)
    REFERENCES `ControleFinanceiro`.`bancos` (`id_banco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cartoes_pessoas1_idx` ON `ControleFinanceiro`.`cartoes` (`pessoa_id` ASC);

CREATE INDEX `fk_cartoes_bancos1_idx` ON `ControleFinanceiro`.`cartoes` (`banco_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pagamento_despesas_variaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`pagamento_despesas_variaveis` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pagamento_despesas_variaveis` (
  `id_pagamento_despesas_variaveis` INT NOT NULL AUTO_INCREMENT,
  `cartao_id` INT NOT NULL,
  `valor` VARCHAR(45) NOT NULL DEFAULT '0.00',
  `forma_de_pagamento` ENUM('Dinheiro', 'Debito', 'Credito', 'Pix') NOT NULL DEFAULT 'Credito',
  `numero_parcelas` INT NOT NULL DEFAULT 1,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id_pagamento_despesas_variaveis`, `cartao_id`),
  CONSTRAINT `fk_pagamento_despesas_variaveis_cartoes1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `ControleFinanceiro`.`cartoes` (`id_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_despesas_variaveis_cartoes1_idx` ON `ControleFinanceiro`.`pagamento_despesas_variaveis` (`cartao_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`despesas_variaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`despesas_variaveis` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`despesas_variaveis` (
  `id_despesas_variaveis` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `categoria_despesas_variaveis_id` INT NOT NULL,
  `pagamento_despesas_variaveis_id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_despesas_variaveis`, `categoria_despesas_variaveis_id`, `pagamento_despesas_variaveis_id`),
  CONSTRAINT `fk_minhas_despesas_variaveis_pagamento_despesas_variaveis1`
    FOREIGN KEY (`pagamento_despesas_variaveis_id`)
    REFERENCES `ControleFinanceiro`.`pagamento_despesas_variaveis` (`id_pagamento_despesas_variaveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minhas_despesas_variaveis_categoria_despesas_fixas1`
    FOREIGN KEY (`categoria_despesas_variaveis_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_minhas_despesas_variaveis_pagamento_despesas_variaveis1_idx` ON `ControleFinanceiro`.`despesas_variaveis` (`pagamento_despesas_variaveis_id` ASC);

CREATE INDEX `fk_minhas_despesas_variaveis_categoria_despesas_fixas1_idx` ON `ControleFinanceiro`.`despesas_variaveis` (`categoria_despesas_variaveis_id` ASC);

CREATE UNIQUE INDEX `codigo_grupo_usuarios_UNIQUE` ON `ControleFinanceiro`.`despesas_variaveis` (`codigo_grupo_usuarios` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`ganhos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`ganhos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`ganhos` (
  `id_ganhos` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `mes_id_mes` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `descricao` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_ganhos`, `mes_id_mes`),
  CONSTRAINT `fk_ganhos_mes1`
    FOREIGN KEY (`mes_id_mes`)
    REFERENCES `ControleFinanceiro`.`meses` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ganhos_mes1_idx` ON `ControleFinanceiro`.`ganhos` (`mes_id_mes` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`tipo_dividas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`tipo_dividas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`tipo_dividas` (
  `id_tipo_divida` INT NOT NULL,
  `tipo` ENUM('boleto', 'crediario', 'cartao', 'financiamento') NOT NULL DEFAULT 'cartao',
  PRIMARY KEY (`id_tipo_divida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`dividas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`dividas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`dividas` (
  `id_minha_divida` INT NOT NULL AUTO_INCREMENT,
  `tipo_divida_id` INT NOT NULL,
  `cartao_id` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `orgao_devedor` VARCHAR(45) NOT NULL,
  `valor_parcela` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `valor_total` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `numero_parcelas` INT(3) NOT NULL DEFAULT 1,
  `data_inicial` DATE NOT NULL DEFAULT current_timestamp,
  `dia_mes_vencimento` INT(2) NOT NULL DEFAULT 2,
  `multa_atraso` DOUBLE(3,2) NULL,
  `juros_por_dia_atraso` DOUBLE(3,2) NULL,
  `desconto_por_dia_adiantado` DOUBLE(3,2) NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` VARCHAR(45) NOT NULL DEFAULT 'current_timestamp on update current_timestamp',
  PRIMARY KEY (`id_minha_divida`, `tipo_divida_id`, `cartao_id`),
  CONSTRAINT `fk_dividas_cartoes1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `ControleFinanceiro`.`cartoes` (`id_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dividas_tipo_dividas1`
    FOREIGN KEY (`tipo_divida_id`)
    REFERENCES `ControleFinanceiro`.`tipo_dividas` (`id_tipo_divida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dividas_cartoes1_idx` ON `ControleFinanceiro`.`dividas` (`cartao_id` ASC);

CREATE INDEX `fk_dividas_tipo_dividas1_idx` ON `ControleFinanceiro`.`dividas` (`tipo_divida_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`tipo_pagamento_dividas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`tipo_pagamento_dividas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`tipo_pagamento_dividas` (
  `id tipo_pagamento_divida` INT NOT NULL,
  `tipo` ENUM('boleto', 'pix', 'credito', 'debito') NULL,
  PRIMARY KEY (`id tipo_pagamento_divida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pagamento_dividas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`pagamento_dividas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pagamento_dividas` (
  `id_pagamento_dividas` INT NOT NULL AUTO_INCREMENT,
  `cartoao_id` INT NOT NULL,
  `minha_divida_id` INT NOT NULL,
  `tipo_pagamento_divida_id` INT NOT NULL,
  `mes_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `numero_parcela_paga` INT NOT NULL DEFAULT 1,
  `valor_desconto` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_juros` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_multa` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_pago` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_pagamento_dividas`, `cartoao_id`, `minha_divida_id`, `tipo_pagamento_divida_id`, `mes_id`),
  CONSTRAINT `fk_pagamento_dividas_minhas_dividas1`
    FOREIGN KEY (`minha_divida_id`)
    REFERENCES `ControleFinanceiro`.`dividas` (`id_minha_divida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_dividas_mes1`
    FOREIGN KEY (`mes_id`)
    REFERENCES `ControleFinanceiro`.`meses` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_dividas_cartoes1`
    FOREIGN KEY (`cartoao_id`)
    REFERENCES `ControleFinanceiro`.`cartoes` (`id_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_dividas_tipo_pagamento_dividas1`
    FOREIGN KEY (`tipo_pagamento_divida_id`)
    REFERENCES `ControleFinanceiro`.`tipo_pagamento_dividas` (`id tipo_pagamento_divida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_dividas_minhas_dividas1_idx` ON `ControleFinanceiro`.`pagamento_dividas` (`minha_divida_id` ASC);

CREATE INDEX `fk_pagamento_dividas_mes1_idx` ON `ControleFinanceiro`.`pagamento_dividas` (`mes_id` ASC);

CREATE INDEX `fk_pagamento_dividas_cartoes1_idx` ON `ControleFinanceiro`.`pagamento_dividas` (`cartoao_id` ASC);

CREATE INDEX `fk_pagamento_dividas_tipo_pagamento_dividas1_idx` ON `ControleFinanceiro`.`pagamento_dividas` (`tipo_pagamento_divida_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`investimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`investimentos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`investimentos` (
  `id_investimento` INT NOT NULL AUTO_INCREMENT,
  `produto_financeiro` VARCHAR(255) NOT NULL,
  `corretora` VARCHAR(45) NOT NULL,
  `tipo_investimento` VARCHAR(45) NOT NULL,
  `valor_plano_mensal` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `numero_meses_plano` INT(3) NOT NULL DEFAULT '1',
  `data_inicial` DATE NOT NULL DEFAULT current_timestamp,
  `rendimento_ao_mes` DOUBLE(2,2) NOT NULL DEFAULT 0.00,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_investimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`valores_investimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`valores_investimento` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`valores_investimento` (
  `id_valores_investimento` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `investimento_id` INT NOT NULL,
  `mes_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `valor_adicionado_amias` DOUBLE(6,2) NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_valores_investimento`, `investimento_id`, `mes_id`),
  CONSTRAINT `fk_valores_investimento_investimentos1`
    FOREIGN KEY (`investimento_id`)
    REFERENCES `ControleFinanceiro`.`investimentos` (`id_investimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valores_investimento_mes1`
    FOREIGN KEY (`mes_id`)
    REFERENCES `ControleFinanceiro`.`meses` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_valores_investimento_investimentos1_idx` ON `ControleFinanceiro`.`valores_investimento` (`investimento_id` ASC);

CREATE INDEX `fk_valores_investimento_mes1_idx` ON `ControleFinanceiro`.`valores_investimento` (`mes_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`limite_gastos_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`limite_gastos_categoria` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`limite_gastos_categoria` (
  `id_limite_gastos_categooria` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `categorias_id` INT NOT NULL,
  `valor_limite_mensal` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_limite_gastos_categooria`, `categorias_id`),
  CONSTRAINT `fk_limite_gastos_categoria_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_limite_gastos_categoria_categorias1_idx` ON `ControleFinanceiro`.`limite_gastos_categoria` (`categorias_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`vencimentos_despesas_fixas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`vencimentos_despesas_fixas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`vencimentos_despesas_fixas` (
  `id_vencimentos_despesas_fixas` INT NOT NULL AUTO_INCREMENT,
  `minha_depesa_fixa_id` INT NOT NULL,
  `dia_mes_vencimento` INT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_vencimentos_despesas_fixas`, `minha_depesa_fixa_id`),
  CONSTRAINT `fk_vencimentos_despesas_fixas_minhas_depesas_fixas1`
    FOREIGN KEY (`minha_depesa_fixa_id`)
    REFERENCES `ControleFinanceiro`.`despesas_fixas` (`id_despesa_fixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vencimentos_despesas_fixas_minhas_depesas_fixas1_idx` ON `ControleFinanceiro`.`vencimentos_despesas_fixas` (`minha_depesa_fixa_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`estabelecimentos_wish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`estabelecimentos_wish` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`estabelecimentos_wish` (
  `id_estabelecimento_wish` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_wish` VARCHAR(255) NOT NULL,
  `site_wish` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estabelecimento_wish`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`categorias_wish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`categorias_wish` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`categorias_wish` (
  `id_categoria_wish` INT NOT NULL AUTO_INCREMENT,
  `categoria_wish` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria_wish`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`produtos_wish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`produtos_wish` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`produtos_wish` (
  `id_produto_wish` INT NOT NULL AUTO_INCREMENT,
  `categoria_wish_id` INT NOT NULL,
  `produto_wish` VARCHAR(45) NOT NULL,
  `descricao_wish` VARCHAR(255) NULL,
  `valor_wish` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id_produto_wish`, `categoria_wish_id`),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_wish_id`)
    REFERENCES `ControleFinanceiro`.`categorias_wish` (`id_categoria_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produto_categoria1_idx` ON `ControleFinanceiro`.`produtos_wish` (`categoria_wish_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`wishlist` (
  `id_wishlist` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `situacao` ENUM('Comprado', 'Nao comprado') NOT NULL DEFAULT 'Nao Comprado',
  PRIMARY KEY (`id_wishlist`, `estabelecimento_id`, `produto_id`),
  CONSTRAINT `fk_wishlist_estabelecimento1`
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES `ControleFinanceiro`.`estabelecimentos_wish` (`id_estabelecimento_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ControleFinanceiro`.`produtos_wish` (`id_produto_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_wishlist_estabelecimento1_idx` ON `ControleFinanceiro`.`wishlist` (`estabelecimento_id` ASC);

CREATE INDEX `fk_wishlist_produto1_idx` ON `ControleFinanceiro`.`wishlist` (`produto_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`metas_financeiras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`metas_financeiras` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`metas_financeiras` (
  `id_metas_financeiras` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `descricao_meta` VARCHAR(255) NOT NULL,
  `categoria` ENUM('Longo Prazo', 'Medio Prazo', 'Curto Prazo') NOT NULL DEFAULT 'Longo Prazo',
  `valor` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
  `prazo_meta` DATE NOT NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_metas_financeiras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(25) NOT NULL,
  `ativo` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `dias_para_expiracao` INT(3) NOT NULL DEFAULT 7,
  `datahora_criacao` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id_usuario`, `pessoa_id`),
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_pessoa1_idx` ON `ControleFinanceiro`.`usuarios` (`pessoa_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`acessos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `acesso` VARCHAR(45) NOT NULL,
  `nivel_acesso` INT(1) NOT NULL,
  `referencia_acesso` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`usuarios_has_acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`usuarios_has_acessos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`usuarios_has_acessos` (
  `usuario_id` INT NOT NULL,
  `acesso_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `acesso_id`),
  CONSTRAINT `fk_usuario_has_acesso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ControleFinanceiro`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_acesso_acesso1`
    FOREIGN KEY (`acesso_id`)
    REFERENCES `ControleFinanceiro`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_acesso_acesso1_idx` ON `ControleFinanceiro`.`usuarios_has_acessos` (`acesso_id` ASC);

CREATE INDEX `fk_usuario_has_acesso_usuario1_idx` ON `ControleFinanceiro`.`usuarios_has_acessos` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`telefones` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero_celular` VARCHAR(15) NOT NULL,
  `numero_telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `tipo_logadouro` VARCHAR(45) NOT NULL DEFAULT 'Rua',
  `logadouro` VARCHAR(255) NOT NULL,
  `bloco` VARCHAR(45) NULL,
  `numero` INT(11) NOT NULL,
  `andar` INT(11) NULL,
  `sala` VARCHAR(6) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` INT(8) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`tipo_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`tipo_pessoas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`tipo_pessoas` (
  `id_tipo_pessoa` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` ENUM('F', 'J') NULL,
  `numero_documento` VARCHAR(22) NULL,
  PRIMARY KEY (`id_tipo_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`grupo_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`grupo_usuarios` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`grupo_usuarios` (
  `codigo_grupo` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`usuario_id`, `codigo_grupo`),
  CONSTRAINT `fk_grupo_usuarios_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ControleFinanceiro`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_grupo_usuarios_usuario1_idx` ON `ControleFinanceiro`.`grupo_usuarios` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`telefones_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`telefones_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`telefones_has_pessoas` (
  `telefone_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`, `pessoa_id`),
  CONSTRAINT `fk_telefone_has_pessoa_telefone1`
    FOREIGN KEY (`telefone_id`)
    REFERENCES `ControleFinanceiro`.`telefones` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefone_has_pessoa_pessoa1_idx` ON `ControleFinanceiro`.`telefones_has_pessoas` (`pessoa_id` ASC);

CREATE INDEX `fk_telefone_has_pessoa_telefone1_idx` ON `ControleFinanceiro`.`telefones_has_pessoas` (`telefone_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`enderecos_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`enderecos_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`enderecos_has_pessoas` (
  `endereco_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`, `pessoa_id`),
  CONSTRAINT `fk_endereco_has_pessoa_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `ControleFinanceiro`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_endereco_has_pessoa_pessoa1_idx` ON `ControleFinanceiro`.`enderecos_has_pessoas` (`pessoa_id` ASC);

CREATE INDEX `fk_endereco_has_pessoa_endereco1_idx` ON `ControleFinanceiro`.`enderecos_has_pessoas` (`endereco_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pessoa_has_tipo_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`pessoa_has_tipo_pessoa` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pessoa_has_tipo_pessoa` (
  `pessoa_id` INT NOT NULL,
  `tipo_pessoa_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`, `tipo_pessoa_id`),
  CONSTRAINT `fk_pessoa_has_tipo_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_tipo_pessoa_tipo_pessoa1`
    FOREIGN KEY (`tipo_pessoa_id`)
    REFERENCES `ControleFinanceiro`.`tipo_pessoas` (`id_tipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pessoa_has_tipo_pessoa_tipo_pessoa1_idx` ON `ControleFinanceiro`.`pessoa_has_tipo_pessoa` (`tipo_pessoa_id` ASC);

CREATE INDEX `fk_pessoa_has_tipo_pessoa_pessoa1_idx` ON `ControleFinanceiro`.`pessoa_has_tipo_pessoa` (`pessoa_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pagamento_despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`pagamento_despesas` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pagamento_despesas` (
  `despesas_id` INT NOT NULL,
  `tipo_despesas` ENUM('F', 'V', 'D') NOT NULL,
  `mes_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `data_pagamento` DATE NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` VARCHAR(45) NOT NULL DEFAULT 'current_timestamp on update current_timestamp',
  PRIMARY KEY (`tipo_despesas`, `despesas_id`, `mes_id`, `ano`),
  CONSTRAINT `fk_pagamento_despesas_mes1`
    FOREIGN KEY (`mes_id`)
    REFERENCES `ControleFinanceiro`.`meses` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pagamento_despesas_mes1_idx` ON `ControleFinanceiro`.`pagamento_despesas` (`mes_id` ASC);


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`cartoes_onlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControleFinanceiro`.`cartoes_onlines` ;

CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`cartoes_onlines` (
  `id_cartao_online` INT NOT NULL AUTO_INCREMENT,
  `cartao_id` INT NOT NULL,
  `numero` VARCHAR(16) NOT NULL,
  `vencimento` VARCHAR(4) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `nome_titular_impresso` VARCHAR(255) NOT NULL,
  `funcao_debito` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `funcao_credito` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`id_cartao_online`, `cartao_id`),
  CONSTRAINT `fk_cartoes_onlines_cartoes1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `ControleFinanceiro`.`cartoes` (`id_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cartoes_onlines_cartoes1_idx` ON `ControleFinanceiro`.`cartoes_onlines` (`cartao_id` ASC);


-- -----------------------------------------------------
-- Data for table `ControleFinanceiro`.`meses`
-- -----------------------------------------------------
START TRANSACTION;
USE `ControleFinanceiro`;
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (1, 'Janeiro');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (2, 'Fevereiro');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (3, 'Março');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (4, 'Abril');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (5, 'Maio');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (6, 'Junho');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (7, 'Julho');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (8, 'Agosto');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (9, 'Setembro');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (10, 'Outubro');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (11, 'Novembro');
INSERT INTO `ControleFinanceiro`.`meses` (`id_mes`, `mes`) VALUES (12, 'Dezembro');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
