-- MySQL Script generated by MySQL Workbench
-- 04/29/24 17:17:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ControleFinanceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ControleFinanceiro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ControleFinanceiro` ;

-- -----------------------------------------------------
-- Schema ControleFinanceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ControleFinanceiro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ControleFinanceiro` ;

-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`mes` (
  `id_mes` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_mes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `tipo_despesas` ENUM('N', 'F', 'V') NOT NULL DEFAULT 'N',
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`depesas_fixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`depesas_fixas` (
  `id_depesas_fixas` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `categoria_despesas_fixas_id` INT NOT NULL,
  `mes_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `descricao` VARCHAR(255) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `numero_parcelas` INT(3) NOT NULL DEFAULT 1,
  `valor_parcela` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `parcelas_pagas` INT(3) NULL DEFAULT 0,
  `status` ENUM('Paga', 'A pagar', 'Pagando') NOT NULL DEFAULT 'A pagar',
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_depesas_fixas`, `categoria_despesas_fixas_id`, `mes_id`),
  INDEX `fk_minhas_depesas_fixas_categoria_despesas_fixas_idx` (`categoria_despesas_fixas_id` ASC),
  INDEX `fk_minhas_depesas_fixas_mes1_idx` (`mes_id` ASC),
  CONSTRAINT `fk_minhas_depesas_fixas_categoria_despesas_fixas`
    FOREIGN KEY (`categoria_despesas_fixas_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minhas_depesas_fixas_mes1`
    FOREIGN KEY (`mes_id`)
    REFERENCES `ControleFinanceiro`.`mes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`cartoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`cartoes` (
  `id_cartoes` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL DEFAULT 'Nubank',
  `funcao_credito` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `funcao_debito` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `limite_credito` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `limite_cheque_especial` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `dia_vencimento_fatura` DATE NOT NULL,
  `cartao_principal` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `encargos` DOUBLE(3,2) NULL,
  `multa` DOUBLE(3,2) NULL,
  `juros` DOUBLE(3,2) NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_cartoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pagamento_despesas_variaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pagamento_despesas_variaveis` (
  `id_pagamento_despesas_variaveis` INT NOT NULL AUTO_INCREMENT,
  `cartao_banco_id` INT NOT NULL,
  `valor` VARCHAR(45) NOT NULL DEFAULT '0.00',
  `forma_de_pagamento` ENUM('Dinheiro', 'Debito', 'Credito', 'Pix') NOT NULL DEFAULT 'Credito',
  `numero_parcelas` INT NOT NULL DEFAULT 1,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id_pagamento_despesas_variaveis`, `cartao_banco_id`),
  INDEX `fk_pagamento_despesas_variaveis_cartao_banco1_idx` (`cartao_banco_id` ASC),
  CONSTRAINT `fk_pagamento_despesas_variaveis_cartao_banco1`
    FOREIGN KEY (`cartao_banco_id`)
    REFERENCES `ControleFinanceiro`.`cartoes` (`id_cartoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`despesas_variaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`despesas_variaveis` (
  `id_despesas_variaveis` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `mes_id_mes` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `categoria_despesas_variaveis_id` INT NOT NULL,
  `pagamento_despesas_variaveis_id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_despesas_variaveis`, `mes_id_mes`, `categoria_despesas_variaveis_id`, `pagamento_despesas_variaveis_id`),
  INDEX `fk_minhas_despesas_variaveis_pagamento_despesas_variaveis1_idx` (`pagamento_despesas_variaveis_id` ASC),
  INDEX `fk_minhas_despesas_variaveis_mes1_idx` (`mes_id_mes` ASC),
  INDEX `fk_minhas_despesas_variaveis_categoria_despesas_fixas1_idx` (`categoria_despesas_variaveis_id` ASC),
  UNIQUE INDEX `codigo_grupo_usuarios_UNIQUE` (`codigo_grupo_usuarios` ASC),
  CONSTRAINT `fk_minhas_despesas_variaveis_pagamento_despesas_variaveis1`
    FOREIGN KEY (`pagamento_despesas_variaveis_id`)
    REFERENCES `ControleFinanceiro`.`pagamento_despesas_variaveis` (`id_pagamento_despesas_variaveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minhas_despesas_variaveis_mes1`
    FOREIGN KEY (`mes_id_mes`)
    REFERENCES `ControleFinanceiro`.`mes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minhas_despesas_variaveis_categoria_despesas_fixas1`
    FOREIGN KEY (`categoria_despesas_variaveis_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`ganhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`ganhos` (
  `id_ganhos` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `mes_id_mes` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `descricao` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_ganhos`, `mes_id_mes`),
  INDEX `fk_ganhos_mes1_idx` (`mes_id_mes` ASC),
  CONSTRAINT `fk_ganhos_mes1`
    FOREIGN KEY (`mes_id_mes`)
    REFERENCES `ControleFinanceiro`.`mes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`dividas` (
  `id_minhas_dividas` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `orgao_devedor` VARCHAR(45) NOT NULL,
  `valor_parcela` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `valor_total` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `numero_parcelas` INT(3) NOT NULL DEFAULT 1,
  `data_inicial` DATE NOT NULL DEFAULT current_timestamp,
  `dia_mes_vencimento` INT(2) NOT NULL DEFAULT 2,
  `multa_atraso` DOUBLE(3,2) NULL,
  `juros_por_dia_atraso` DOUBLE(3,2) NULL,
  `desconto_por_dia_adiantado` DOUBLE(3,2) NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` VARCHAR(45) NOT NULL DEFAULT 'current_timestamp on update current_timestamp',
  PRIMARY KEY (`id_minhas_dividas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pagamento_dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pagamento_dividas` (
  `id_pagamento_dividas` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `mes_id_mes` INT NOT NULL,
  `minhas_dividas_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `numero_parcela_paga` INT NOT NULL DEFAULT 1,
  `valor_desconto` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_juros` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_multa` DOUBLE(3,2) NULL DEFAULT 0.00,
  `valor_pago` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_pagamento_dividas`, `mes_id_mes`, `minhas_dividas_id`),
  INDEX `fk_pagamento_dividas_minhas_dividas1_idx` (`minhas_dividas_id` ASC),
  INDEX `fk_pagamento_dividas_mes1_idx` (`mes_id_mes` ASC),
  CONSTRAINT `fk_pagamento_dividas_minhas_dividas1`
    FOREIGN KEY (`minhas_dividas_id`)
    REFERENCES `ControleFinanceiro`.`dividas` (`id_minhas_dividas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_dividas_mes1`
    FOREIGN KEY (`mes_id_mes`)
    REFERENCES `ControleFinanceiro`.`mes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`investimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`investimentos` (
  `id_investimentos` INT NOT NULL AUTO_INCREMENT,
  `produto_financeiro` VARCHAR(255) NOT NULL,
  `corretora` VARCHAR(45) NOT NULL,
  `tipo_investimento` VARCHAR(45) NOT NULL,
  `valor_plano_mensal` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `numero_meses_plano` INT(3) NOT NULL DEFAULT '1',
  `data_inicial` DATE NOT NULL DEFAULT current_timestamp,
  `rendimento_ao_mes` DOUBLE(2,2) NOT NULL DEFAULT 0.00,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_investimentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`valores_investimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`valores_investimento` (
  `id_valores_investimento` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `investimentos_id` INT NOT NULL,
  `mes_id` INT NOT NULL,
  `ano` INT(4) NOT NULL DEFAULT 2024,
  `valor_adicionado_amias` DOUBLE(6,2) NULL DEFAULT 0.00,
  `data_hora` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL DEFAULT 'kaiuviny',
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_valores_investimento`, `investimentos_id`, `mes_id`),
  INDEX `fk_valores_investimento_investimentos1_idx` (`investimentos_id` ASC),
  INDEX `fk_valores_investimento_mes1_idx` (`mes_id` ASC),
  CONSTRAINT `fk_valores_investimento_investimentos1`
    FOREIGN KEY (`investimentos_id`)
    REFERENCES `ControleFinanceiro`.`investimentos` (`id_investimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valores_investimento_mes1`
    FOREIGN KEY (`mes_id`)
    REFERENCES `ControleFinanceiro`.`mes` (`id_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`limite_gastos_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`limite_gastos_categoria` (
  `id_limite_gastos_categooria` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `categorias_id` INT NOT NULL,
  `valor_limite_mensal` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_limite_gastos_categooria`, `categorias_id`),
  INDEX `fk_limite_gastos_categoria_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_limite_gastos_categoria_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `ControleFinanceiro`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`vencimentos_despesas_fixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`vencimentos_despesas_fixas` (
  `id_vencimentos_despesas_fixas` INT NOT NULL AUTO_INCREMENT,
  `minhas_depesas_fixas_id` INT NOT NULL,
  `dia_mes_vencimento` INT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_vencimentos_despesas_fixas`, `minhas_depesas_fixas_id`),
  INDEX `fk_vencimentos_despesas_fixas_minhas_depesas_fixas1_idx` (`minhas_depesas_fixas_id` ASC),
  CONSTRAINT `fk_vencimentos_despesas_fixas_minhas_depesas_fixas1`
    FOREIGN KEY (`minhas_depesas_fixas_id`)
    REFERENCES `ControleFinanceiro`.`depesas_fixas` (`id_depesas_fixas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`estabelecimentos_wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`estabelecimentos_wish` (
  `id_estabelecimento_wish` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_wish` VARCHAR(255) NOT NULL,
  `site_wish` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estabelecimento_wish`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`categorias_wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`categorias_wish` (
  `id_categoria_wish` INT NOT NULL AUTO_INCREMENT,
  `categoria_wish` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria_wish`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`produtos_wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`produtos_wish` (
  `id_produto_wish` INT NOT NULL AUTO_INCREMENT,
  `categoria_wish_id` INT NOT NULL,
  `produto_wish` VARCHAR(45) NOT NULL,
  `descricao_wish` VARCHAR(255) NULL,
  `_wish` DOUBLE(6,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id_produto_wish`, `categoria_wish_id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_wish_id` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_wish_id`)
    REFERENCES `ControleFinanceiro`.`categorias_wish` (`id_categoria_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`wishlist` (
  `id_wishlist` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `situacao` ENUM('Comprado', 'Nao comprado') NOT NULL DEFAULT 'Nao Comprado',
  PRIMARY KEY (`id_wishlist`, `estabelecimento_id`, `produto_id`),
  INDEX `fk_wishlist_estabelecimento1_idx` (`estabelecimento_id` ASC),
  INDEX `fk_wishlist_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_wishlist_estabelecimento1`
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES `ControleFinanceiro`.`estabelecimentos_wish` (`id_estabelecimento_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ControleFinanceiro`.`produtos_wish` (`id_produto_wish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`metas_financeiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`metas_financeiras` (
  `id_metas_financeiras` INT NOT NULL AUTO_INCREMENT,
  `codigo_grupo_usuarios` VARCHAR(45) NOT NULL,
  `descricao_meta` VARCHAR(255) NOT NULL,
  `categoria` ENUM('Longo Prazo', 'Medio Prazo', 'Curto Prazo') NOT NULL DEFAULT 'Longo Prazo',
  `valor` DOUBLE(8,2) NOT NULL DEFAULT 0.00,
  `prazo_meta` DATE NOT NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_metas_financeiras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pessoas` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `segundo_nome` VARCHAR(45) NULL,
  `terceiro_nome` VARCHAR(45) NULL,
  `sobre_nome` VARCHAR(45) NOT NULL,
  `segundo_sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `datetime_create` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `user_update` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(25) NOT NULL,
  `ativo` ENUM('Y', 'N') NOT NULL DEFAULT 'Y',
  `dias_para_expiracao` INT(3) NOT NULL DEFAULT 7,
  `datahora_criacao` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id_usuario`, `pessoa_id`),
  INDEX `fk_usuario_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `acesso` VARCHAR(45) NOT NULL,
  `nivel_acesso` INT(1) NOT NULL,
  `referencia_acesso` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`usuarios_has_acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`usuarios_has_acessos` (
  `usuario_id` INT NOT NULL,
  `acesso_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `acesso_id`),
  INDEX `fk_usuario_has_acesso_acesso1_idx` (`acesso_id` ASC),
  INDEX `fk_usuario_has_acesso_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_acesso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ControleFinanceiro`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_acesso_acesso1`
    FOREIGN KEY (`acesso_id`)
    REFERENCES `ControleFinanceiro`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero_celular` VARCHAR(15) NOT NULL,
  `numero_telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(255) NOT NULL,
  `bloco` VARCHAR(45) NULL,
  `numero` INT(11) NOT NULL,
  `andar` INT(11) NULL,
  `sala` VARCHAR(6) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` INT(8) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`tipo_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`tipo_pessoas` (
  `id_tipo_pessoa` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` ENUM('F', 'J') NULL,
  `numero_documento` VARCHAR(22) NULL,
  PRIMARY KEY (`id_tipo_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`grupo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`grupo_usuarios` (
  `codigo_grupo` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`usuario_id`, `codigo_grupo`),
  INDEX `fk_grupo_usuarios_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_grupo_usuarios_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ControleFinanceiro`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`telefones_has_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`telefones_has_pessoas` (
  `telefone_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`telefone_id`, `pessoa_id`),
  INDEX `fk_telefone_has_pessoa_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_telefone_has_pessoa_telefone1_idx` (`telefone_id` ASC),
  CONSTRAINT `fk_telefone_has_pessoa_telefone1`
    FOREIGN KEY (`telefone_id`)
    REFERENCES `ControleFinanceiro`.`telefones` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`enderecos_has_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`enderecos_has_pessoas` (
  `endereco_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`, `pessoa_id`),
  INDEX `fk_endereco_has_pessoa_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_endereco_has_pessoa_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_endereco_has_pessoa_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `ControleFinanceiro`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_has_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControleFinanceiro`.`pessoa_has_tipo_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControleFinanceiro`.`pessoa_has_tipo_pessoa` (
  `pessoa_id` INT NOT NULL,
  `tipo_pessoa_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`, `tipo_pessoa_id`),
  INDEX `fk_pessoa_has_tipo_pessoa_tipo_pessoa1_idx` (`tipo_pessoa_id` ASC),
  INDEX `fk_pessoa_has_tipo_pessoa_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_pessoa_has_tipo_pessoa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `ControleFinanceiro`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_tipo_pessoa_tipo_pessoa1`
    FOREIGN KEY (`tipo_pessoa_id`)
    REFERENCES `ControleFinanceiro`.`tipo_pessoas` (`id_tipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

